export const npcChart =
[
    {
        CR: 0.25,
        Level: 0.5,
        Prof: 2,
        AC: 12,
        HP: 15,
        Saves: 2,
        DmgRound: 6,
        ToHit: 4,
        DC: 11,
        SpellToHit: 3,
        SpellLevel: 0,
        Points: 24,
    },
    {
        CR: 1,
        Level: 2,
        Prof: 2,
        AC: 13,
        HP: 30,
        Saves: 3,
        DmgRound: 12,
        ToHit: 4.5,
        DC: 11.5,
        SpellToHit: 3.5,
        SpellLevel: 1,
        Points: 30,
    },
    {
        CR: 2,
        Level: 4,
        Prof: 2,
        AC: 14,
        HP: 45,
        Saves: 4,
        DmgRound: 18,
        ToHit: 5,
        DC: 12,
        SpellToHit: 4,
        SpellLevel: 2,
        Points: 35,
    },
    {
        CR: 3,
        Level: 4,
        Prof: 2,
        AC: 14,
        HP: 60,
        Saves: 6,
        DmgRound: 24,
        ToHit: 5.5,
        DC: 12.5,
        SpellToHit: 4.5,
        SpellLevel: 2,
        Points: 40,
    },
    {
        CR: 4,
        Level: 6,
        Prof: 2,
        AC: 14,
        HP: 75,
        Saves: 7,
        DmgRound: 30,
        ToHit: 6,
        DC: 13,
        SpellToHit: 5,
        SpellLevel: 3,
        Points: 45,
    },
    {
        CR: 5,
        Level: 9,
        Prof: 3,
        AC: 15,
        HP: 90,
        Saves: 9,
        DmgRound: 36,
        ToHit: 6.5,
        DC: 13.5,
        SpellToHit: 5.5,
        SpellLevel: 3,
        Points: 51,
    },
    {
        CR: 6,
        Level: 10,
        Prof: 3,
        AC: 15,
        HP: 105,
        Saves: 10,
        DmgRound: 42,
        ToHit: 7,
        DC: 14,
        SpellToHit: 6,
        SpellLevel: 4,
        Points: 55,
    },
    {
        CR: 7,
        Level: 11,
        Prof: 3,
        AC: 15,
        HP: 120,
        Saves: 12,
        DmgRound: 48,
        ToHit: 7.5,
        DC: 14.5,
        SpellToHit: 6.5,
        SpellLevel: 4,
        Points: 60,
    },
    {
        CR: 8,
        Level: 14,
        Prof: 3,
        AC: 16,
        HP: 135,
        Saves: 13,
        DmgRound: 54,
        ToHit: 8,
        DC: 15,
        SpellToHit: 7,
        SpellLevel: 5,
        Points: 66,
    },
    {
        CR: 9,
        Level: 16,
        Prof: 4,
        AC: 16,
        HP: 150,
        Saves: 15,
        DmgRound: 60,
        ToHit: 8.5,
        DC: 15.5,
        SpellToHit: 7.5,
        SpellLevel: 5,
        Points: 71,
    },
    {
        CR: 10,
        Level: 17,
        Prof: 4,
        AC: 16,
        HP: 165,
        Saves: 16,
        DmgRound: 66,
        ToHit: 9,
        DC: 16,
        SpellToHit: 8,
        SpellLevel: 6,
        Points: 75,
    },
    {
        CR: 11,
        Level: 18,
        Prof: 4,
        AC: 17,
        HP: 180,
        Saves: 18,
        DmgRound: 72,
        ToHit: 9.5,
        DC: 16.5,
        SpellToHit: 8.5,
        SpellLevel: 7,
        Points: 81,
    },
    {
        CR: 12,
        Level: 19,
        Prof: 4,
        AC: 17,
        HP: 195,
        Saves: 19,
        DmgRound: 78,
        ToHit: 10,
        DC: 17,
        SpellToHit: 9,
        SpellLevel: 7,
        Points: 86,
    },
    {
        CR: 13,
        Level: 20,
        Prof: 5,
        AC: 17,
        HP: 210,
        Saves: 21,
        DmgRound: 84,
        ToHit: 10.5,
        DC: 17.5,
        SpellToHit: 9.5,
        SpellLevel: 8,
        Points: 91,
    },
    {
        CR: 14,
        Level: 21,
        Prof: 5,
        AC: 18,
        HP: 225,
        Saves: 22,
        DmgRound: 90,
        ToHit: 11,
        DC: 18,
        SpellToHit: 10,
        SpellLevel: 8,
        Points: 96,
    },
    {
        CR: 15,
        Level: 22,
        Prof: 5,
        AC: 18,
        HP: 240,
        Saves: 24,
        DmgRound: 96,
        ToHit: 11.5,
        DC: 18.5,
        SpellToHit: 10.5,
        SpellLevel: 8,
        Points: 101,
    },
    {
        CR: 16,
        Level: 23,
        Prof: 5,
        AC: 18,
        HP: 255,
        Saves: 25,
        DmgRound: 102,
        ToHit: 12,
        DC: 19,
        SpellToHit: 11,
        SpellLevel: 9,
        Points: 106,
    },
    {
        CR: 17,
        Level: 24,
        Prof: 6,
        AC: 19,
        HP: 270,
        Saves: 27,
        DmgRound: 108,
        ToHit: 12.5,
        DC: 19.5,
        SpellToHit: 11.5,
        SpellLevel: 9,
        Points: 112,
    },
    {
        CR: 18,
        Level: 25,
        Prof: 6,
        AC: 19,
        HP: 285,
        Saves: 28,
        DmgRound: 114,
        ToHit: 13,
        DC: 20,
        SpellToHit: 12,
        SpellLevel: 9,
        Points: 116,
    },
    {
        CR: 19,
        Level: 26,
        Prof: 6,
        AC: 19,
        HP: 300,
        Saves: 30,
        DmgRound: 120,
        ToHit: 13.5,
        DC: 20.5,
        SpellToHit: 12.5,
        SpellLevel: 9,
        Points: 121,
    },
    {
        CR: 20,
        Level: 27,
        Prof: 6,
        AC: 20,
        HP: 315,
        Saves: 31,
        DmgRound: 126,
        ToHit: 14,
        DC: 21,
        SpellToHit: 13,
        SpellLevel: 9,
        Points: 127,
    },
    {
        CR: 21,
        Level: 28,
        Prof: 7,
        AC: 20,
        HP: 330,
        Saves: 33,
        DmgRound: 132,
        ToHit: 14.5,
        DC: 21.5,
        SpellToHit: 13.5,
        SpellLevel: 9,
        Points: 132,
    },
    {
        CR: 22,
        Level: 29,
        Prof: 7,
        AC: 20,
        HP: 345,
        Saves: 34,
        DmgRound: 138,
        ToHit: 15,
        DC: 22,
        SpellToHit: 14,
        SpellLevel: 9,
        Points: 136,
    },
    {
        CR: 23,
        Level: 30,
        Prof: 7,
        AC: 21,
        HP: 360,
        Saves: 36,
        DmgRound: 144,
        ToHit: 15.5,
        DC: 22.5,
        SpellToHit: 14.5,
        SpellLevel: 9,
        Points: 142,
    },
    {
        CR: 24,
        Level: 31,
        Prof: 7,
        AC: 21,
        HP: 375,
        Saves: 37,
        DmgRound: 150,
        ToHit: 16,
        DC: 23,
        SpellToHit: 15,
        SpellLevel: 9,
        Points: 147,
    },
    {
        CR: 25,
        Level: 32,
        Prof: 8,
        AC: 21,
        HP: 390,
        Saves: 39,
        DmgRound: 156,
        ToHit: 16.5,
        DC: 23.5,
        SpellToHit: 15.5,
        SpellLevel: 9,
        Points: 152,
    },
    {
        CR: 26,
        Level: 33,
        Prof: 8,
        AC: 22,
        HP: 405,
        Saves: 40,
        DmgRound: 162,
        ToHit: 17,
        DC: 24,
        SpellToHit: 16,
        SpellLevel: 9,
        Points: 157,
    },
    {
        CR: 27,
        Level: 34,
        Prof: 8,
        AC: 22,
        HP: 420,
        Saves: 42,
        DmgRound: 168,
        ToHit: 17.5,
        DC: 24.5,
        SpellToHit: 16.5,
        SpellLevel: 9,
        Points: 162,
    },
    {
        CR: 28,
        Level: 35,
        Prof: 8,
        AC: 22,
        HP: 435,
        Saves: 43,
        DmgRound: 174,
        ToHit: 18,
        DC: 25,
        SpellToHit: 17,
        SpellLevel: 9,
        Points: 167,
    },
    {
        CR: 29,
        Level: 36,
        Prof: 9,
        AC: 23,
        HP: 450,
        Saves: 45,
        DmgRound: 180,
        ToHit: 18.5,
        DC: 25.5,
        SpellToHit: 17.5,
        SpellLevel: 9,
        Points: 173,
    },
    {
        CR: 30,
        Level: 37,
        Prof: 9,
        AC: 23,
        HP: 465,
        Saves: 46,
        DmgRound: 186,
        ToHit: 19,
        DC: 26,
        SpellToHit: 18,
        SpellLevel: 9,
        Points: 177,
    },
];
