export const npcChart = [
    {
        cr: 0.25,
        level: 0.5,
        proficiency: 2,
        ac: 12,
        hp: 15,
        dmg: 6,
        hit: 4,
        dc: 11,
        spellHit: 3,
        spellLevel: 0,
        points: 24,
    },
    {
        cr: 1,
        level: 2,
        proficiency: 2,
        ac: 13,
        hp: 30,
        dmg: 12,
        hit: 4,
        dc: 11,
        spellHit: 3,
        spellLevel: 1,
        points: 29,
    },
    {
        cr: 2,
        level: 4,
        proficiency: 2,
        ac: 14,
        hp: 45,
        dmg: 18,
        hit: 5,
        dc: 12,
        spellHit: 4,
        spellLevel: 2,
        points: 35,
    },
    {
        cr: 3,
        level: 4,
        proficiency: 2,
        ac: 14,
        hp: 60,
        dmg: 24,
        hit: 5,
        dc: 12,
        spellHit: 4,
        spellLevel: 2,
        points: 39,
    },
    {
        cr: 4,
        level: 6,
        proficiency: 2,
        ac: 14,
        hp: 75,
        dmg: 30,
        hit: 6,
        dc: 13,
        spellHit: 5,
        spellLevel: 3,
        points: 44,
    },
    {
        cr: 5,
        level: 9,
        proficiency: 3,
        ac: 15,
        hp: 90,
        dmg: 36,
        hit: 6,
        dc: 13,
        spellHit: 5,
        spellLevel: 3,
        points: 49,
    },
    {
        cr: 6,
        level: 10,
        proficiency: 3,
        ac: 15,
        hp: 105,
        dmg: 42,
        hit: 7,
        dc: 14,
        spellHit: 6,
        spellLevel: 4,
        points: 54,
    },
    {
        cr: 7,
        level: 11,
        proficiency: 3,
        ac: 15,
        hp: 120,
        dmg: 48,
        hit: 7,
        dc: 14,
        spellHit: 6,
        spellLevel: 4,
        points: 58,
    },
    {
        cr: 8,
        level: 14,
        proficiency: 3,
        ac: 16,
        hp: 135,
        dmg: 54,
        hit: 8,
        dc: 15,
        spellHit: 7,
        spellLevel: 5,
        points: 64,
    },
    {
        cr: 9,
        level: 16,
        proficiency: 4,
        ac: 16,
        hp: 150,
        dmg: 60,
        hit: 8,
        dc: 15,
        spellHit: 7,
        spellLevel: 5,
        points: 68,
    },
    {
        cr: 10,
        level: 17,
        proficiency: 4,
        ac: 16,
        hp: 165,
        dmg: 66,
        hit: 9,
        dc: 16,
        spellHit: 8,
        spellLevel: 6,
        points: 73,
    },
    {
        cr: 11,
        level: 18,
        proficiency: 4,
        ac: 17,
        hp: 180,
        dmg: 72,
        hit: 9,
        dc: 16,
        spellHit: 8,
        spellLevel: 7,
        points: 78,
    },
    {
        cr: 12,
        level: 19,
        proficiency: 4,
        ac: 17,
        hp: 195,
        dmg: 78,
        hit: 10,
        dc: 17,
        spellHit: 9,
        spellLevel: 7,
        points: 83,
    },
    {
        cr: 13,
        level: 20,
        proficiency: 5,
        ac: 17,
        hp: 210,
        dmg: 84,
        hit: 10,
        dc: 17,
        spellHit: 9,
        spellLevel: 8,
        points: 87,
    },
    {
        cr: 14,
        level: 21,
        proficiency: 5,
        ac: 18,
        hp: 225,
        dmg: 90,
        hit: 11,
        dc: 18,
        spellHit: 10,
        spellLevel: 8,
        points: 93,
    },
    {
        cr: 15,
        level: 22,
        proficiency: 5,
        ac: 18,
        hp: 240,
        dmg: 96,
        hit: 11,
        dc: 18,
        spellHit: 10,
        spellLevel: 8,
        points: 97,
    },
    {
        cr: 16,
        level: 23,
        proficiency: 5,
        ac: 18,
        hp: 255,
        dmg: 102,
        hit: 12,
        dc: 19,
        spellHit: 11,
        spellLevel: 9,
        points: 102,
    },
    {
        cr: 17,
        level: 24,
        proficiency: 6,
        ac: 19,
        hp: 270,
        dmg: 108,
        hit: 12,
        dc: 19,
        spellHit: 11,
        spellLevel: 9,
        points: 107,
    },
    {
        cr: 18,
        level: 25,
        proficiency: 6,
        ac: 19,
        hp: 285,
        dmg: 114,
        hit: 13,
        dc: 20,
        spellHit: 12,
        spellLevel: 9,
        points: 112,
    },
    {
        cr: 19,
        level: 26,
        proficiency: 6,
        ac: 19,
        hp: 300,
        dmg: 120,
        hit: 13,
        dc: 20,
        spellHit: 12,
        spellLevel: 9,
        points: 116,
    },
    {
        cr: 20,
        level: 27,
        proficiency: 6,
        ac: 20,
        hp: 315,
        dmg: 126,
        hit: 14,
        dc: 21,
        spellHit: 13,
        spellLevel: 9,
        points: 122,
    },
    {
        cr: 21,
        level: 28,
        proficiency: 7,
        ac: 20,
        hp: 330,
        dmg: 132,
        hit: 14,
        dc: 21,
        spellHit: 13,
        spellLevel: 9,
        points: 126,
    },
    {
        cr: 22,
        level: 29,
        proficiency: 7,
        ac: 20,
        hp: 345,
        dmg: 138,
        hit: 15,
        dc: 22,
        spellHit: 14,
        spellLevel: 9,
        points: 131,
    },
    {
        cr: 23,
        level: 30,
        proficiency: 7,
        ac: 21,
        hp: 360,
        dmg: 144,
        hit: 15,
        dc: 22,
        spellHit: 14,
        spellLevel: 9,
        points: 136,
    },
    {
        cr: 24,
        level: 31,
        proficiency: 7,
        ac: 21,
        hp: 375,
        dmg: 150,
        hit: 16,
        dc: 23,
        spellHit: 15,
        spellLevel: 9,
        points: 141,
    },
    {
        cr: 25,
        level: 32,
        proficiency: 8,
        ac: 21,
        hp: 390,
        dmg: 156,
        hit: 16,
        dc: 23,
        spellHit: 15,
        spellLevel: 9,
        points: 145,
    },
    {
        cr: 26,
        level: 33,
        proficiency: 8,
        ac: 22,
        hp: 405,
        dmg: 162,
        hit: 17,
        dc: 24,
        spellHit: 16,
        spellLevel: 9,
        points: 151,
    },
    {
        cr: 27,
        level: 34,
        proficiency: 8,
        ac: 22,
        hp: 420,
        dmg: 168,
        hit: 17,
        dc: 24,
        spellHit: 16,
        spellLevel: 9,
        points: 155,
    },
    {
        cr: 28,
        level: 35,
        proficiency: 8,
        ac: 22,
        hp: 435,
        dmg: 174,
        hit: 18,
        dc: 25,
        spellHit: 17,
        spellLevel: 9,
        points: 160,
    },
    {
        cr: 29,
        level: 36,
        proficiency: 9,
        ac: 23,
        hp: 450,
        dmg: 180,
        hit: 18,
        dc: 25,
        spellHit: 17,
        spellLevel: 9,
        points: 165,
    },
    {
        cr: 30,
        level: 37,
        proficiency: 9,
        ac: 23,
        hp: 465,
        dmg: 186,
        hit: 19,
        dc: 26,
        spellHit: 18,
        spellLevel: 9,
        points: 170,
    },
];
